name: Build & Deploy Spring application

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build & Deploy Spring boot application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # - name: Unit Tests
      #   run: mvn -B test --file backend/pom.xml

      - name: Build BE the application
        run:
          mvn clean package --file backend/pom.xml

      - name: Build BE Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-exe-spring

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push BE to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/backend-exe-spring
          
      - name: Deploy BE to AWS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SERVER_HOST }}
          username: ${{ secrets.AWS_SERVER_USERNAME }}
          key: ${{ secrets.AWS_SERVER_SSH_KEY }}
          port: ${{ secrets.AWS_SERVER_SSH_PORT }}
          script: |
            sudo docker pull ${DOCKER_HUB_USERNAME}/backend-exe-spring:latest
            sudo docker stop backend-exe-spring || true
            sudo docker rm backend-exe-spring || true
            sudo docker run -d --name backend-exe-spring -p 80:8086 ${DOCKER_HUB_USERNAME}/backend-exe-spring:latest
            

          
